/*...........................................................................................*/
/*.....................................ANNIE.................................................*/
/*...........................................................................................*/
CREATE TABLE PERSONAS(
  COD_PERSONA    BIGINT PRIMARY KEY AUTO_INCREMENT   COMMENT 'CODIGO DE PERSONA'
, NOM_PERSONA    VARCHAR(100) NOT NULL         		   COMMENT 'NOMBRE DE LA PERSONA'
, SEX_PERSONA    ENUM('F','M') NOT NULL              COMMENT 'SEXO DE LA PERSONA'
, EDAD_PERSONAL  TINYINT  NOT NULL                   COMMENT 'EDAD DE LA PERSONA'
, TIP_PERSONA    ENUM('P','C','A') NOT NULL          COMMENT 'Tipo de Documento'
, Num_Identidad  VARCHAR(15) NOT NULL                COMMENT 'Numero de Identidad'
, IND_CIVIL      ENUM('S','C','D','V') NOT NULL    	 COMMENT 'Estado civil de la persona'
, IND_PERSONA    ENUM('1','0') NOT NULL              COMMENT 'ESTADO DE LA PERSONA'            
, FEC_REGISTRO   DATETIME NOT NULL                   COMMENT 'FECHA QUE SE REGISTRA LA TUPLA' 
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE ROL(
       COD_ROL      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA ROL'
       ,COD_PERSONA  BIGINT                           COMMENT 'CODIGO PERSONA'
       ,ROL_PER       VARCHAR(30) not null             COMMENT 'NOMBRE'
       ,DESCR  VARCHAR(100) null
       ,ESTADO      bit not null	
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;



CREATE TABLE TELEFONOS(
 COD_TELEFONO  BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA TELEFONOS'
 ,COD_PERSONA  BIGINT                            COMMENT 'CODIGO PERSONA'
 ,NUM_TELEFONO int(15) NOT NULL                  COMMENT 'NUMERO TELEFENO'
 ,TIP_TELEFONO ENUM('P','C','T')                 COMMENT 'TIPO DE TELEFONO'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


CREATE TABLE DIRECCIONES(
 COD_DIR BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO DIRECCION'
,COD_PERSONA    BIGINT                     COMMENT 'CODIGO PERSONA'
,DIRECCION     VARCHAR (100) NOT NULL      COMMENT 'CODIGO DIRRECION'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


CREATE TABLE CORREOS(
COD_COR  BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA'
,COD_PERSONA  BIGINT                       COMMENT 'CODIGO PERSONA'
,CORREO VARCHAR(50) NOT NULL               COMMENT 'CORREO'
,CONTRASEÑA VARCHAR(50) NOT NULL           COMMENT 'CONTRA'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


CREATE TABLE USUARIOS(
       COD_USR  BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA',
       COD_PERSONA  BIGINT                        COMMENT 'CODIGO PERSONA'                      
       ,COD_ROL  BIGINT                           COMMENT 'CODIGO ROL'
       ,COD_COR BIGINT                            COMMENT 'CODIGO COR'
       ,COD_DIR BIGINT                            COMMENT 'CODIGO DIRECCION'
       ,COD_TELEFONO BIGINT                       COMMENT 'CODIGO TELEFONO'
       ,estado bit not null
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;




/*...........................................................................................*/
/*.......................................KEVIN...............................................*/
/*...........................................................................................*/

CREATE TABLE FABRICANTE(
  COD_EMPRESA  BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO DE LA EMPRESA'
, PROVEEDORES VARCHAR(255) NOT NULL              COMMENT 'NOMBRE DE LA EMPRESA'
, DIR_EMPRESA VARCHAR(255) NOT NULL              COMMENT 'DIRECCION DE LA EMPRESA'
, TEL_EMPRESA VARCHAR(16) NOT NULL               COMMENT 'TELEFONO DE LA EMPRESA'
, COR_EMPRESA VARCHAR(255) NOT NULL              COMMENT 'CORREO ELECTRONICO DE LA EMPRESA'
, NOM_PRODUCTO VARCHAR(255) NOT NULL             COMMENT 'nombre del producto'
, UNIDADES INT NOT NULL                          COMMENT 'Numero de unidades del producto'
, COS_PRODUCTO VARCHAR(255) NOT NULL             COMMENT 'COSTO DEL PRODCUTO'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


CREATE TABLE ENPRODUCCION(

 COD_ARTICULO  BIGINT PRIMARY KEY AUTO_INCREMENT  COMMENT 'CODIGO DEL PRODUCTO'
,COD_EMPRESA   BIGINT                             COMMENT 'CODIGO DE LA EMPRESA'
, NOM_PROD_EN VARCHAR(255) NOT NULL               COMMENT 'NOMBRE DEL PRODUCTO'
, CAN_PRODUCTO VARCHAR(255) NOT NULL              COMMENT 'CANTIDAD DEL PRODUCTO'
, COS_PROD_EN  VARCHAR(255) NOT NULL              COMMENT 'COSTO DEL PRODCUTO'

)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;



/*...........................................................................................*/
/*........................................JORGE..............................................*/
/*...........................................................................................*/

CREATE TABLE PRODUCTO (
COD_PRODUCTO  BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID del producto'
,COD_EMPRESA  BIGINT not null 
,NOM_PRODUCTO VARCHAR(20) NOT NULL COMMENT 'Nombre del producto' 
,PROVEEDOR VARCHAR (20) NOT NULL COMMENT 'Nombre del proveedor del producto'
,MARCA VARCHAR (20) NOT NULL COMMENT 'Nombre de la marca del producto'
,PRECIO INT NOT NULL COMMENT 'Precio del producto'
,UNIDADES INT NOT NULL COMMENT 'Numero de unidades del producto'
)ENGINE= INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE INVENTARIO(
COD_INV  BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Codigo del inVENTArio'
,COD_PRODUCTO  BIGINT not null
,COD_EMPRESA  BIGINT not null
,NOM_PRODUCTOS VARCHAR(20) NOT NULL       COMMENT 'Nombre del producto'
,PROVEEDORES VARCHAR(20) NOT NULL         COMMENT 'Nombre de los proveedores'
,MARCA VARCHAR (20) NOT NULL              COMMENT 'Nombre de la marca del producto'
,UNIDADES INT NOT NULL                    COMMENT 'Numero de unidades del producto'
,CATEGORIAS VARCHAR(20) 
)ENGINE= INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;



/*...........................................................................................*/
/*........................................EMERSON..............................................*/
/*...........................................................................................*/


CREATE TABLE VENTAS(
        COD_VENTA         BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO VENTA'
       ,COD_INV           BIGINT
       ,COD_PERSONA       BIGINT
       ,COD_PRODUCTO      BIGINT 
       ,NOM_PRODUCTO      VARCHAR(255)  NOT NULL            COMMENT 'NOMPRE DEL PRODUCTO'
       ,CANT_PRODUCTO     TINYINT       NOT NULL            COMMENT 'CANTIDAD DEL PRODUCTO'
       ,PREC_UNITARIO     INT           NOT NULL            COMMENT 'PRECIO DEL PRODUCTO'
       ,TOTAL_BRUTO       BIGINT       NOT NULL            COMMENT 'VENTA TOTAL'
       ,DESTINO_VENTA     VARCHAR (255) NOT NULL            COMMENT 'DESTINO DEL PRODUCTO'
       ,FEC_VENTA         DATETIME      NOT NULL            COMMENT 'FECHA EN QUE SE REALIZO LA VENTA'
       ,IMPUE_TOTAL       DECIMAL (4,2) NOT NULL            COMMENT 'IMPUESTO DE VENTA'
       ,TOTAL_VENTA       DECIMAL (11,2) NOT NULL           COMMENT 'VENTA TOTAL'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


CREATE TABLE COMPRAS(
        COD_COMPRA       BIGINT PRIMARY KEY AUTO_INCREMENT         COMMENT 'LLAVE PRIMARIA COMPRA'
       ,COD_EMPRESA      BIGINT 
       ,COD_PERSONA      BIGINT
       ,NOM_PROD         VARCHAR(55)   NOT NULL                     COMMENT 'NOMPRE DEL PRODUCTO'
       ,DEST_PROD        VARCHAR(20)     NOT NULL                   COMMENT 'DESTINO DEL PRODUCTO'
       ,FEC_COMP         DATETIME       NOT NULL                    COMMENT 'FECHA EN QUE SE REALIZO LA VENTA'
       ,DEST_CATEG       VARCHAR(20)     NOT NULL                   COMMENT 'DESTINO DE CATEGORIA'
       ,CANT_PROD        TINYINT        NOT NULL                    COMMENT 'CANTIDAD DEL PRODUCTO'
       ,PREC_COMP        INT        NOT NULL                       COMMENT 'PRECIO DE COMPRA'
       ,IMPU_COMP        DECIMAL (4,2)  NOT NULL                   COMMENT 'IMPUESTO DE COMPRA'
       ,TOL_COMP         DECIMAL (11,2) NOT NULL                   COMMENT 'TOTAL A PAGAR'
   
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


/*...........................................................................................*/
/*.............................................ANA.........................................*/
/*...........................................................................................*/

CREATE TABLE DistribProduct(
cod_departamento  BIGINT primary key auto_increment,
 COD_PERSONA      BIGINT,
 COD_PRODUCTO      BIGINT,
 COD_VENTA         BIGINT,
nombreDepart VARCHAR(30) not null,
lugar_entrega VARCHAR(60) not null,
nombre VARCHAR(100) not null
)ENGINE = INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;




CREATE TABLE Descproducto(
cod_descproducto  BIGINT primary key auto_increment,
COD_PRODUCTO      BIGINT,
nombreproduct VARCHAR(30) not null,
precioproduct int(10) not null,
cantidadproduct int(10) not null,
color VARCHAR(20) not null,
tamano VARCHAR(30) not  null
)ENGINE = INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


/*________________________________Annie_______________________________*/


CREATE TABLE ROLPER(
       COD_ROLPER     BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA'
       ,COD_ROL        BIGINT                           COMMENT 'CODIGO DE ROL'
       ,COD_PERSONA    BIGINT                           COMMENT 'CODIGO PERSONA'
       ,FOREIGN KEY `FK_ROLPER`(COD_PERSONA) REFERENCES PERSONAS (COD_PERSONA) ON DELETE CASCADE
       ,FOREIGN KEY `FK_PERROL`(COD_ROL) REFERENCES ROL (COD_ROL) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE PERTEL(
        COD_PERTEL     BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA'
       ,COD_TELEFONO   BIGINT                            COMMENT 'CODIGO TELEFONO'
       ,COD_PERSONA    BIGINT                            COMMENT 'CODIGO PERSONA'
       ,FOREIGN KEY `FK_PERTEL`(COD_PERSONA) REFERENCES  PERSONAS (COD_PERSONA) ON DELETE CASCADE
       ,FOREIGN KEY `FK_TELPER`(COD_TELEFONO) REFERENCES TELEFONOS (COD_TELEFONO) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE PERDIR(
        COD_PERDIR     BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Id ROL'
       ,COD_DIR        BIGINT                            COMMENT 'CODIGO DE DIRRECIONES'
       ,COD_PERSONA    BIGINT                            COMMENT 'CODIGO PERSONA'
       ,FOREIGN KEY `FK_PERDIR`(COD_PERSONA) REFERENCES PERSONAS (COD_PERSONA) ON DELETE CASCADE
       ,FOREIGN KEY `FK_DIRPER`(COD_DIR) REFERENCES DIRECCIONES (COD_DIR) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE PERCOR(
        COD_PERCOR     BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA'
       ,COD_COR        BIGINT                            COMMENT 'CODIGO CORREO'
       ,COD_PERSONA    BIGINT                            COMMENT 'CODIGO PERSONA'
       ,FOREIGN KEY `FK_PERCOR`(COD_PERSONA) REFERENCES PERSONAS (COD_PERSONA) ON DELETE CASCADE
       ,FOREIGN KEY `FK_CORPER`(COD_COR) REFERENCES CORREOS (COD_COR) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE PERUSR(
        COD_PERUSR     BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA '
       ,COD_USR        BIGINT                            COMMENT 'CODIGO USUARIO'
       ,COD_PERSONA    BIGINT                            COMMENT 'CODIGO PERSONA'
       ,COD_ROL  BIGINT                                  COMMENT 'CODIGO ROL'
       ,COD_COR BIGINT                                   COMMENT 'CODIGO COR'
       ,COD_DIR BIGINT                                   COMMENT 'CODIGO DIRECCION'
       ,COD_TELEFONO BIGINT                              COMMENT 'CODIGO TELEFONO'
       ,FOREIGN KEY `FK_PERUSR`(COD_PERSONA) REFERENCES PERSONAS (COD_PERSONA) ON DELETE CASCADE
       ,FOREIGN KEY `FK_USRPER`(COD_USR) REFERENCES USUARIOS (COD_USR) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

/*________________________________Kevin_______________________________*/



CREATE TABLE REL_FABENP( 
     COD_RELFABENPRO    BIGINT PRIMARY KEY AUTO_INCREMENT  COMMENT 'LLAVE PRIMARIA RELACIONPERSONAS'
    ,COD_ARTICULO       BIGINT                             COMMENT 'LLAVE PRIMARIA TABLA ENPRODUCCION'
    ,COD_EMPRESA        BIGINT                             COMMENT  'LLAVE PRIMARIA TABLA FABRICANTE'
,FOREIGN KEY `FK_FAB_ENP` (COD_EMPRESA)REFERENCES FABRICANTE (COD_EMPRESA) ON DELETE CASCADE
,FOREIGN KEY `FK_ENP_FAB` (COD_ARTICULO)REFERENCES ENPRODUCCION (COD_ARTICULO ) ON DELETE CASCADE
)ENGINE=INNODB 
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE REL_FABINV( 
     COD_FABINV BIGINT PRIMARY KEY AUTO_INCREMENT  COMMENT 'LLAVE PRIMARIA RELACIONPERSONAS'
    ,COD_INV         BIGINT                             COMMENT 'LLAVE PRIMARIA TABLA ROL'
    ,COD_EMPRESA    BIGINT                             COMMENT  'LLAVE PRIMARIA TABLA TELEFONO'
,FOREIGN KEY `FK_FAB_INV` (COD_EMPRESA)REFERENCES FABRICANTE (COD_EMPRESA) ON DELETE CASCADE
,FOREIGN KEY `FK_INV_FAB` (COD_INV)REFERENCES INVENTARIO (COD_INV ) ON DELETE CASCADE
)ENGINE=INNODB 
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE REL_ENPINV( 
     COD_ENPINV BIGINT PRIMARY KEY AUTO_INCREMENT  COMMENT 'LLAVE PRIMARIA S'
    ,COD_INV         BIGINT                             COMMENT 'LLAVE PRIMARIA TABLA INVENTARIO'
    ,COD_ARTICULO    BIGINT                             COMMENT  'LLAVE PRIMARIA TABLA EMPRESA'
,FOREIGN KEY `FK_ENP_INV` (COD_ARTICULO)REFERENCES ENPRODUCCION (COD_ARTICULO) ON DELETE CASCADE
,FOREIGN KEY `FK_INV_ENP` (COD_INV)REFERENCES INVENTARIO (COD_INV) ON DELETE CASCADE
)ENGINE=INNODB 
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;





/*________________________________jorge_______________________________*/


CREATE TABLE REL_PRODINV(
COD_PRODINV BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Codigo de la relacion'
,COD_PRODUCTO BIGINT                           COMMENT 'Codigo deL producto'
,COD_INV BIGINT                                COMMENT 'Codigo deL inventario'
,FOREIGN KEY `FK_PRODREL`(COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO) ON DELETE CASCADE
,FOREIGN KEY `FK_INVREL`(COD_INV) REFERENCES INVENTARIO(COD_INV) ON DELETE CASCADE
)ENGINE= INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

/*________________________________Emerson_______________________________*/


CREATE TABLE RELVENINV(
     COD_RELVENINV      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE TABLA'
    ,COD_VENTA          BIGINT                            COMMENT 'LLAVE PRIMARIA VENTA'
    ,COD_INV            BIGINT                            COMMENT 'LLAVE PRIMARIA INVENTARIO'
    ,FOREIGN KEY `FK_RELVENINV` (COD_INV) REFERENCES INVENTARIO (COD_INV) ON DELETE CASCADE 
    ,FOREIGN KEY `FK_RELINVVEN` (COD_VENTA) REFERENCES VENTAS (COD_VENTA) ON DELETE CASCADE 
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE RELVENPER(
     COD_RELVENPER      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA'
    ,COD_VENTA          BIGINT                            COMMENT 'LLAVE PRIMARIA VENTA'
    ,COD_PERSONA        BIGINT                            COMMENT 'LLAVE PRIMARIA PERSONA'
    ,FOREIGN KEY `FK_RELVENPER` (COD_PERSONA) REFERENCES PERSONAS (COD_PERSONA) ON DELETE CASCADE 
    ,FOREIGN KEY `FK_RELPERVEN` (COD_VENTA) REFERENCES VENTAS (COD_VENTA) ON DELETE CASCADE 
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE RELVENPROD(
     COD_RELVENPROD      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA'
    ,COD_VENTA           BIGINT                             COMMENT 'LLAVE PRIMARIA VENTA'
    ,COD_PRODUCTO        BIGINT                            COMMENT 'LLAVE PRIMARIA PRODUCTO'
    ,FOREIGN KEY `FK_RELVENPROD` (COD_VENTA) REFERENCES VENTAS (COD_VENTA) ON DELETE CASCADE 
    ,FOREIGN KEY `FK_RELPRODVEN` (COD_PRODUCTO) REFERENCES PRODUCTO (COD_PRODUCTO) ON DELETE CASCADE 
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

/*-----------------------------COMPRAS-----------------------------------------*/

CREATE TABLE RELCOMFAB(
     COD_RELCOMFAB      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA'
    ,COD_COMPRA         BIGINT                            COMMENT 'LLAVE PRIMARIA COMPRA'
    ,COD_EMPRESA        BIGINT                            COMMENT 'LLAVE PRIMARIA PERSONA'
    ,FOREIGN KEY `FK_RELCOMFAB` (COD_EMPRESA) REFERENCES FABRICANTE (COD_EMPRESA) ON DELETE CASCADE 
    ,FOREIGN KEY `FK_RELFABCOM` (COD_COMPRA) REFERENCES COMPRAS (COD_COMPRA) ON DELETE CASCADE 
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE RELCOMPERS(
     COD_RELCOMPERS      BIGINT PRIMARY KEY AUTO_INCREMENT  COMMENT 'LLAVE PRIMARIA'
    ,COD_COMPRA         BIGINT                             COMMENT 'LLAVE PRIMARIA COMPRA'
    ,COD_PERSONA        BIGINT                             COMMENT 'LLAVE PRIMARIA PRODUCTO'
    ,FOREIGN KEY `FK_RELCOMPPER`(COD_COMPRA) REFERENCES COMPRAS(COD_COMPRA) ON DELETE CASCADE 
    ,FOREIGN KEY `FK_RELPERCOM` (COD_PERSONA) REFERENCES PERSONAS (COD_PERSONA) ON DELETE CASCADE 
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

/*________________________________Ana_______________________________*/


CREATE TABLE REL_DISTRIBPR(
COD_REL_DISTRIBPR BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA'
,COD_PERSONA BIGINT
,cod_departamento BIGINT
 ,FOREIGN KEY `FK_TDISTRIBPR_TPERSODISTRIB`(COD_PERSONA) REFERENCES PERSONAS(COD_PERSONA) ON DELETE CASCADE
 ,FOREIGN KEY `FK_TPERSODISTRIB_TDISTRIBPR`(cod_departamento) REFERENCES DistribProduct(cod_departamento) ON DELETE CASCADE
)ENGINE = INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


CREATE TABLE REL_DISTPROD(
COD_REL_DISTPROD BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA'
,cod_departamento BIGINT
,COD_PRODUCTO BIGINT
,FOREIGN KEY `FK_PRODDISTRIB_TDISTPRO`(cod_departamento) REFERENCES DistribProduct(cod_departamento) ON DELETE CASCADE
,FOREIGN KEY `FK_TDISTRIBPROD`(COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO) ON DELETE CASCADE
)ENGINE = INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE REL_DISTVEN(
COD_REL_DISTVEN BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA',
COD_VENTA  BIGINT
,cod_departamento BIGINT 
,FOREIGN KEY `FK_TDISTVEN_VENTADISTRIB`(COD_VENTA) REFERENCES VENTAS(COD_VENTA) ON DELETE CASCADE
,FOREIGN KEY `FK_VENTADISTRIB_TDISTVEN`(cod_departamento) REFERENCES DistribProduct(cod_departamento) ON DELETE CASCADE
)ENGINE = INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE REL_DESPRO(
COD_REL_DESPRO BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA',
COD_PRODUCTO  BIGINT,
cod_descproducto BIGINT
,FOREIGN KEY `FK_TDESPRO_TPRODUCTODES`(COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO) ON DELETE CASCADE
,FOREIGN KEY `FK_PRODDES_TDESPROD`(cod_descproducto) REFERENCES descproducto(cod_descproducto) ON DELETE CASCADE
)ENGINE = INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;






/*----------------------------------JAIRO--------------------------------------------------------*/
CREATE TABLE `reportpersonas` (
  `COD_REPORTPERSONAS` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE REPORTE DE PERSONAS',
  `COD_ROL` bigint(20) DEFAULT NULL COMMENT 'CODIGO DE ROL',
  `ROL_PER` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE',
  `COD_PERSONA` bigint(20) DEFAULT NULL COMMENT 'CODIGO PERSONA',
  `NOM_PERSONA` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA PERSONA',
  `COD_TELEFONO` bigint(20) DEFAULT NULL COMMENT 'CODIGO TELEFONO',
  `COD_DIR` bigint(20) DEFAULT NULL COMMENT 'CODIGO DE DIRRECIONES',
  `COD_COR` bigint(20) DEFAULT NULL COMMENT 'CODIGO CORREO',
  `COD_USR` bigint(20) DEFAULT NULL COMMENT 'CODIGO USUARIO',
  PRIMARY KEY (`COD_REPORTPERSONAS`),
  KEY `FK_ROLPER2` (`COD_PERSONA`),
  KEY `FK_PERROL1` (`COD_ROL`),
  KEY `FK_TELPER1` (`COD_TELEFONO`),
  KEY `FK_CORPER1` (`COD_COR`),
  KEY `FK_USRPER1` (`COD_USR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `reportcompra` (
  `COD_REPORTCOMPRA` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE REPORTE DE COMPRA',
  `COD_COMPRA` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA COMPRA',
  `COD_INV` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA INVENTARIO',
  `CATEGORIAS` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `COD_PERSONA` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA PERSONA',
  `NOM_PERSONA` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA PERSONA',
  `COD_VENTA` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA COMPRA',
  `COD_PRODUCTO` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA PRODUCTO',
  `NOM_PRODUCTO` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DEL PRODUCTO',
  PRIMARY KEY (`COD_REPORTCOMPRA`),
  KEY `FK_RELCOMINV1` (`COD_INV`),
  KEY `FK_RELINVCOM1` (`COD_COMPRA`),
  KEY `FK_RELCOMPER1` (`COD_PERSONA`),
  KEY `FK_RELCOMPROD1` (`COD_VENTA`),
  KEY `FK_RELPRODCOM1` (`COD_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `reportproduccion` (
  `COD_REPORTPRODUCCION` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE REPORTE DE PRODUCCION',
  `COD_ARTICULO` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA TABLA ENPRODUCCION',
  `NOM_PRODUCTO` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DEL PRODUCTO',
  `COD_EMPRESA` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA TABLA FABRICANTE',
  `PROVEEDORES` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA EMPRESA',
  `COD_INV` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA TABLA ROL',
  `CATEGORIAS` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`COD_REPORTPRODUCCION`),
  KEY `FK_FAB_ENP1` (`COD_EMPRESA`),
  KEY `FK_ENP_FAB1` (`COD_ARTICULO`),
  KEY `FK_INV_FAB1` (`COD_INV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `reportinventario` (
  `COD_REPORTINVENTARIO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE REPORTE DE INVENTARIO',
  `COD_PRODUCTO` bigint(20) DEFAULT NULL COMMENT 'Codigo deL producto',
  `NOM_PRODUCTO` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DEL PRODUCTO',
  `COD_INV` bigint(20) DEFAULT NULL COMMENT 'Codigo deL inventario',
  `CATEGORIAS` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`COD_REPORTINVENTARIO`),
  KEY `FK_PRODREL1` (`COD_PRODUCTO`),
  KEY `FK_INVREL1` (`COD_INV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `reportventa` (
  `COD_REPORTVENTA` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE REPORTE DE VENTA',
  `COD_VENTA` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA VENTA',
  `COD_INV` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA INVENTARIO',
  `CATEGORIAS` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `COD_PERSONA` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA PERSONA',
  `NOM_PERSONA` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA PERSONA',
  `COD_PRODUCTO` bigint(20) DEFAULT NULL COMMENT 'LLAVE PRIMARIA PRODUCTO',
  `NOM_PRODUCTO` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DEL PRODUCTO',
  PRIMARY KEY (`COD_REPORTVENTA`),
  KEY `FK_RELVENINV1` (`COD_INV`),
  KEY `FK_RELINVVEN1` (`COD_VENTA`),
  KEY `FK_RELVENPER1` (`COD_PERSONA`),
  KEY `FK_RELPRODVEN1` (`COD_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `reportdistribucion` (
  `COD_REPORTDISTRIBUCION` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE REPORTE DE DISTRIBUCION',
  `COD_PERSONA` bigint(20) DEFAULT NULL,
  `NOM_PERSONA` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA PERSONA',
  `COD_VENTA` bigint(20) DEFAULT NULL,
  `COD_PRODUCTO` bigint(20) DEFAULT NULL,
  `NOM_PRODUCTO` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DEL PRODUCTO',
  `COD_INV` bigint(20) DEFAULT NULL,
  `CATEGORIAS` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `COD_ARTICULO` bigint(20) DEFAULT NULL,
  `cod_descproducto` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`COD_REPORTDISTRIBUCION`),
  KEY `FK_TDISTRIBPR_TPERSODISTRIB1` (`COD_PERSONA`),
  KEY `FK_VENTDISTRIB1` (`COD_VENTA`),
  KEY `FK_TDISTRIBPROD1` (`COD_PRODUCTO`),
  KEY `FK_TDISTINV_TINVENTARIODISTRIB1` (`COD_INV`),
  KEY `FK_ENPDESC1` (`COD_ARTICULO`),
  KEY `FK_DESCDESC1` (`cod_descproducto`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `reportgeneral` (
  `COD_REPORTGENERAL` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DEL REPORTE GENERAL',
  `COD_REPORTPERSONAS` bigint(20) DEFAULT NULL COMMENT 'CODIGO DE REPORTE DE PERSONAS',
  `NOM_PERSONA` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA PERSONA',
  `COD_REPORTPRODUCCION` bigint(20) DEFAULT NULL COMMENT 'CODIGO DE REPORTE DE PRODUCCION',
  `PROVEEDORES` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA EMPRESA',
  `COD_REPORTINVENTARIO` bigint(20) DEFAULT NULL COMMENT 'CODIGO DE REPORTE DE INVENTARIO',
  `CATEGORIAS` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `COD_REPORTVENTA` bigint(20) DEFAULT NULL COMMENT 'CODIGO DE REPORTE DE VENTA',
  `COD_REPORTCOMPRA` bigint(20) DEFAULT NULL COMMENT 'CODIGO DE REPORTE DE COMPRA',
  `COD_REPORTDISTRIBUCION` bigint(20) DEFAULT NULL COMMENT 'CODIGO DE REPORTE DE DISTRIBUCION',
  PRIMARY KEY (`COD_REPORTGENERAL`),
  KEY `FK_RE_PERSONA` (`COD_REPORTPERSONAS`),
  KEY `FK_RE_PRODUCCION` (`COD_REPORTPRODUCCION`),
  KEY `FK_RE_INVENTARIO` (`COD_REPORTINVENTARIO`),
  KEY `FK_RE_VENTA` (`COD_REPORTVENTA`),
  KEY `FK_RE_COMPRA` (`COD_REPORTCOMPRA`),
  KEY `FK_RE_DISTRIBUCION` (`COD_REPORTDISTRIBUCION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;